# LEARNING PYTHON PRACTICES

In [2]:
# Let's get two numbers from the user, and print out their sum

user_input = input("Enter 2 numbers separated by space: ")

user_list = user_input.split()

print("List: ", user_list)

user_sum = 0;

for i in user_list:
    user_sum += int(i)
    
print(user_sum)


Enter 2 numbers separated by space: 7 8 9
List:  ['7', '8', '9']
24


In [4]:
# Let's get two lists from the user and concatenate them

user_i1 = input("Enter at least 3 numbers separated by space: ")
user_i2 = input("Enter another list with other numbers: ")

in1 = user_i1.split()
in2 = user_i2.split()

print("List 1 is: ", in1, "List 2 is: ", in2)

final_list = in1 + in2

print("Final list is: ", final_list)

Enter at least 3 numbers separated by space: 7 8 8 9
Enter another list with other numbers: 3 4 5 67
List 1 is:  ['7', '8', '8', '9'] List 2 is:  ['3', '4', '5', '67']
Final list is:  ['7', '8', '8', '9', '3', '4', '5', '67']


In [11]:
# Earnings calculation

salary = int(input("Enter your salary: "))
bonus = int(input("Enter your bonus: "))

if salary < 0 or bonus < 0:
    print("Your salary or bonus can not be negative")
else:
    if salary > bonus:
        print("Your erned: ", salary+bonus)
    else:
        print("Your salary is {} and it is less than your bonus, it is not possible.".format(salary))

Enter your salary: -233
Enter your bonus: 2772
Your salary or bonus can not be negative


In [12]:
# students information from y1 to y3

reg_num = input("Enter REG Num: ")

y1 = int(input("Enter y1 marks: "))
y2 = int(input("Enter y2 marks: "))
y3 = int(input("Enter y3 marks: "))

if (not reg_num):
    print("Please add your REG Number!")
else:
    z= ((y1 + y2 + y3)*100)/3
    print("Congratulations! Your REG Number is {} and you have graduated with {}%.".format(reg_num, z))

# print(student_data)



Enter REG Num: 34
Enter y1 marks: 45
Enter y2 marks: 344
Enter y3 marks: 34
Congratulations! Your REG Number is 34 and you have graduated with 14100.0%.


In [27]:
# For Loop

final_salaries = []

bonus_percent = 10
top_salary = 200

salary = eval(input("Enter your salaries: "))

for i in range (len(salary)):
    if salary[i] < 0:
        print("One of your salaries is negative!")
        break
    bonus = (salary[i] *  bonus_percent) / 100
    if salary[i] < top_salary:
        total_salary = salary[i] + bonus
    else:
        total_salary = salary[i]
    final_salaries.append(total_salary)
    if len(final_salaries) == len(salary):
        print(final_salaries)

Enter your salaries: 100,50,30,40,50,60,300
[110.0, 55.0, 33.0, 44.0, 55.0, 66.0, 300]


In [30]:
# For Each 2

list = [10,30,50,20,60,70]

for num in list:
    if(num > 50):
        print(num)

60
70


In [36]:
# Function
salary = int(input("Enter your salary: "))

def calcutate_bonus(salary, percentage):
    return (salary*percentage)/100


z = calcutate_bonus(salary,20)

print ("Your salary is {}, so your bonus is {}. Means you will be paid {} RWF.".format(salary, z, salary + z))

Enter your salary: 900909
Your salary is 900909, so your bonus is 180181.8. Means you will be paid 1081090.8 RWF.


In [4]:
# SP

money_earned = int(input("Enter the amount earned: "))
people_to_pay = input("Enter names of people to pay separated by comma: ")
people_to_pay.split(",")
percent_to_pay = [50,40,10]

def calculate_percent_amount(p):
    return (money_earned*p) / 100

def calculate_individually():
    total_amount = calculate_percent_amount(percent_to_pay[0])
    individual_pay = total_amount / len(people_to_pay)
    
    return individual_pay

def left_money():
    company_amount = calculate_percent_amount(percent_to_pay[1])
    company_amount_no_ref = calculate_percent_amount(percent_to_pay[0])
    ref_amount = calculate_percent_amount(percent_to_pay[2])
    pay = calculate_individually()
    referer = input("Do we have a referrer? Y/N ")
  
    if referer == "Y":
        ref_name = input("Enter his/name: ")
        print("{} is a referrer and will be paid {} RWF.".format(ref_name, ref_amount))
        print("Company will get {} RWF.".format(ref_name, company_amount))
    else:
        print("The company will get {} RWF.".format(company_amount_no_ref))
        
    for person in people_to_pay:
        print("{} will be paid {}".format(person, pay))
    
left_money()
            
            

Enter the amount earned: 100000
Enter names of people to pay separated by comma: G N
Do we have a referrer? Y/N n
The company will get 50000.0 RWF.
G will be paid 16666.666666666668
  will be paid 16666.666666666668
N will be paid 16666.666666666668


In [5]:
# OOP IN PYTHON

class Person:
    hair = "blonde"
    legs = "long"
    def assign_id(self, name, age, home):
        self.name = name
        self.age = age
        self.home = home
    def get_id(self):
        print(self.name)
        
pers = Person()

pers.assign_id("Ganza", 20, "Kacyiru")
pers.get_id()

Ganza


In [2]:
# Assignment on Dictionaries

class StudentRecords:
    
    # Empty dictionary that will store student unmodified info
    stInfo = {}
    
    # A method to set student info into the dictionary
    def setStInfo(self, name, y1, y2, y3):
        self.stInfo[name] = [name, [y1,y2,y3]]
    
    # Display student information stored in a dictionary
    def getStudents(self):
        print(self.stInfo)
        
    # Calculate the total marks and percentage
    def totalMarks(self):
        finalInfo = {} # Store the disctionaly with sum of marks
        finalInfoPercent = {} # Store the dictionary with percentages
        
        # Loop through dictionary data
        for p in self.stInfo:
            marks = self.stInfo[p][1]
            
            # Calculate the sum of marks
            s = 0
            for m in marks:
                s += m
            #Percentage calculation 
            percentage = (s * 100)/300
            
            finalInfo[p] = [p, s] # Information with total marks
            finalInfoPercent[p] = [p, int(percentage)] # Information with percentages
            
        print(finalInfo)
        print(finalInfoPercent)
                

In [4]:
std = StudentRecords()

std.setStInfo("Gakuru", 100,100,100)
std.setStInfo("Senzoga", 100,62,50)
std.setStInfo("Remure", 100,67,23)


std.getStudents()

print("-------------------------------------------------------------------------------------------------------------")

std.totalMarks()

{'Gakuru': ['Gakuru', [100, 100, 100]], 'Senzoga': ['Senzoga', [100, 62, 50]], 'Remure': ['Remure', [100, 67, 23]]}
-------------------------------------------------------------------------------------------------------------
{'Gakuru': ['Gakuru', 300], 'Senzoga': ['Senzoga', 212], 'Remure': ['Remure', 190]}
{'Gakuru': ['Gakuru', 100], 'Senzoga': ['Senzoga', 70], 'Remure': ['Remure', 63]}


In [ ]:
# Constructor



In [1]:
def my_fun_2(x, y):
    p = x * y
    s = x + y
    return p, s

In [9]:
def my_func():
    a = input("Enter number 1: ")
    b = input("Enter number 2: ")
    print("The product of your numbers is {} and the sum is {}.".format(my_fun_2(int(a), int(b))[0], my_fun_2(int(a), int(b))[1]))

In [11]:
my_func()

Enter number 1: 6
Enter number 2: 9
The product of your numbers is 54 and the sum is 15.


In [12]:
!pip install numpy

In [6]:
import numpy as np

In [7]:
my_list = [1,2,3,5,6,7,8,9,10,11,45,67]
print(len(my_list))

numpy_arr = np.array(my_list)
print(numpy_arr)

12
[ 1  2  3  5  6  7  8  9 10 11 45 67]


In [27]:
matrix_arr = numpy_arr.reshape(4,3)

print(matrix_arr)

# for i in range(3):
#     print(matrix_arr[i])

    
# Print the matrix of [1,6], [3,8]

matrix_arr[0:2, :2]

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [11 45 67]]


array([[1, 2],
       [5, 6]])

In [8]:
# Assignment: Make a class with 3 functions. Input data, Process data, and output results.

In [1]:
# My self made module that is used to calculate age, while you provided year of birth

import CalculateAge 

In [6]:
myage = CalculateAge.CalculateAge()

print(type(myage))

myage.giveYob()
myage.calculateHere()
myage.getAge()

<class 'CalculateAge.CalculateAge'>
Enter your Year Of Birth: 2002


21

In [2]:
# A module that calculate the average, and sum of marks by taking in the students info and marks from 3 years.

import AverageCalc 

In [2]:
student = AverageCalc.AverageCalc()



student.setStInfo()
student.getStudents()
student.totalMarks()

Enter your name: Achille
Enter Y1 marks: 23
Enter Y2 marks: 45
Enter Y3 marks: 78
{'Achille': ['Achille', [23, 45, 78]]}
This is the total of your marks:  {'Achille': ['Achille', 146]}
This is your marks per cent:  {'Achille': 48}
This is your marks average:  48.666666666666664


In [16]:
# class of hotels

class Hotels:
    # Using a constructor
    def __init__(self, name, location, category):
        self.name = name
        self.location = location
        self.category = category
    def getHotels(self):
        print("{} is a {} hotel, located at {}.".format(self.name, self.category, self.location))
        
hotel = Hotels("Serena", "Nyarugenge", "5 Star")
hotel1 = Hotels("Radisson", "Gasabo", "5 Star")

In [17]:
# hotel = Hotels()

# print(type(hotel))

hotel.getHotels()
hotel1.getHotels()

Serena is a 5 Star hotel, located at Nyarugenge.
Radisson is a 5 Star hotel, located at Gasabo.


In [16]:
# Computers

# class of hotels

class Computers:
    # Using a constructor
    def __init__(self, make, kind, price):
        self.make = make
        self.kind = kind
        self.price = price
        print("A computer of {} kind, is made by {}, and bought at {} RWF.".format(self.kind, self.make, self.price))
    def updatePrice(self, newPrice):
        self.price = newPrice

pricey = []

c1 = Computers("Dell", "i5", 300000)
pricey.append(c1.price)
c2 = Computers("Apple", "Mojo", 200000)
pricey.append(c2.price)

def totalPrice(prices):
    s = 0
    for p in prices:
        s+=p
    print("All computers can be bought at {} RWF.".format(s))

totalPrice(pricey)

A computer of i5 kind, is made by Dell, and bought at 300000 RWF.
A computer of Mojo kind, is made by Apple, and bought at 200000 RWF.
All computers can be bought at 500000 RWF.


In [4]:
# Python inheritance

class Computation:
    salary = 0
    def bonusCompute(self, sal, rate):
        self.bonus = sal * rate
        return self.bonus
    def salaryComp(self, b_sal, bonus):
        self.bonus = bonus
        self.b_sal = b_sal
        bonus = self.bonusCompute(b_sal, bonus)
        self.salary = int(b_sal) + int(bonus)
    
class salaryCompute(Computation):

    def setData(self):
        self.s = int(input("Enter your salary: "))
        self.b = float(input("Enter your bonus rate: "))
        self.getSalary()
    def getSalary(self):
        ob = Computation()
        ob.salaryComp(self.s, self.b)
        if ob.salary < 0:
            print("You can not add the negative salary. Try again!")
            self.setData()
        elif ob.salary > 1000000:
            print("We don't pay you that much! Please add your respective salary.")
            self.setData()
        else:
            print("The total salary is: ", ob.salary)

In [5]:
achille = salaryCompute()

achille.setData()


Enter your salary: 5000
Enter your bonus rate: 0.4
The total salary is:  7000


In [9]:
import os

In [16]:
# Files

file = open('/home/yt-achille/Desktop/average.txt', 'r') # r means reading, if you want to write to the file, you change the letter to w
# file.write("Ikechwukwu")
file.read()

'Ikechwukwu'

In [11]:
file.close()

In [8]:
import json
import os.path

In [19]:
# Make a class, a student will enter names, reg num, marks and lessons and save those data to the file.

class FileOps:
    stInfo = {}
    
    def addData(self):
        for i in range(3):
            name = input("Enter your name: ")
            regNum = input("Enter your reg number: ")
            marks = eval(input("Enter marks for Four lessons separated with comma : "))
            infoOne = [name, regNum, ["AI", marks[0]], ["Python", marks[1]], ["IoT", marks[2]], ["Algorithm", marks[3]]]
            self.stInfo[name] = infoOne
            self.i=+1
        self.getData()
        self.saveData()
    def createFile(self):
        self.dataDB = open("/home/yt-achille/Desktop/learning-python-repo/stInfo.txt", "w")
        
    def getData(self):
        print(self.stInfo)
        
    def saveData(self):
        if(not os.path.isfile("/home/yt-achille/Desktop/learning-python-repo/stInfo.txt")):
            self.createFile()
            print("File created!\n\n")
        else:
            print("File already exists!")
        self.dataDB = open("/home/yt-achille/Desktop/learning-python-repo/stInfo.txt", "a")
        self.dataDB.writelines(json.dumps(self.stInfo))
        print("Data saved successfully!\n\n")
        self.fileClose()
        self.readFile()
    def readFile(self):
        self.dataDB = open("/home/yt-achille/Desktop/learning-python-repo/stInfo.txt", "r")
        self.dataDB.read()
        self.fileClose()
    def fileClose(self):
        self.dataDB.close()

In [18]:
# obj = FileOps("Songa", "20RP01904", ["Math", "Geo"], [30,78])
# obj1 = FileOps("SongaS", "20RP019042", ["Math1", "Geo"], [32,75])
obj = FileOps()
obj.addData()


Enter your name: s
Enter your reg number: 2
Enter marks for Four lessons separated with comma : 23,45,32,12
Enter your name: r
Enter your reg number: 44
Enter marks for Four lessons separated with comma : 45,34,23,45
Enter your name: t
Enter your reg number: 54
Enter marks for Four lessons separated with comma : 65,34,54,67
{'s': ['s', '2', ['AI', 23], ['Python', 45], ['IoT', 32], ['Algorithm', 12]], 'r': ['r', '44', ['AI', 45], ['Python', 34], ['IoT', 23], ['Algorithm', 45]], 't': ['t', '54', ['AI', 65], ['Python', 34], ['IoT', 54], ['Algorithm', 67]]}
File already exists!
Data saved successfully!




In [20]:
pip install virtualenv

Note: you may need to restart the kernel to use updated packages.
